### ISSUE TITLE
Tracking issue for the layer system

### ISSUE THREAD

**Issue by AMNatty** [plutoengine/plutoengine#4]
The layer system is currently *very broken*.

Tasks required for a basic setup:

- [x] Layer traversal in order
- [ ] Correctly handling systems on layer stack traversal
- [x] Correctly handling layer dependency trees 
- [ ] Correct attaching behavior
- [ ] Waiting for all dependencies to attach before attaching the parent
- [ ] Correct detaching behavior
- [ ] Waiting for all dependencies to attach before detaching the parent
